from typing import Optional

class ProtoKey:
    """Method prototype: return type + parameter types."""

    def __new__(cls, return_type: str, params: list[str] = ...) -> ProtoKey: ...
    @staticmethod
    def from_descriptor(desc: str) -> Optional[ProtoKey]:
        """Parse ``"([Ljava/lang/String;)V"`` into a :class:`ProtoKey`."""
        ...

    @property
    def return_type(self) -> str: ...
    @property
    def params(self) -> list[str]: ...
    def shorty(self) -> str: ...

class CodeDef:
    """Assembled code item returned by :meth:`CodeBuilder.build`."""

    @property
    def registers(self) -> int: ...
    @property
    def ins(self) -> int: ...
    @property
    def outs(self) -> int: ...
    @property
    def insns_count(self) -> int: ...

class CodeBuilder:
    """Assembles Dalvik bytecode from disassembly text lines.

    The builder is consumed by :meth:`build`; any further calls raise
    :exc:`ValueError`.
    """

    def __new__(cls, registers: int, ins: int, outs: int) -> CodeBuilder: ...

    def emit(self, line: str) -> None:
        """Parse and emit one disassembly line (e.g. ``"return-void"``)."""
        ...

    def label(self, name: str) -> None:
        """Place a named label at the current instruction position."""
        ...

    def build(self) -> CodeDef:
        """Resolve branches and return a :class:`CodeDef`.

        The builder is consumed after this call.
        """
        ...

class IrFieldDef:
    """A field declaration inside a class IR."""

    def __new__(
        cls, name: str, field_type: str, access_flags: int = 0
    ) -> IrFieldDef: ...

    @property
    def name(self) -> str: ...
    @property
    def field_type(self) -> str: ...
    @property
    def access_flags(self) -> int: ...
    @access_flags.setter
    def access_flags(self, v: int) -> None: ...

class IrMethodDef:
    """A method declaration (optionally with a body)."""

    def __new__(
        cls, name: str, descriptor: str, access_flags: int = 0
    ) -> IrMethodDef: ...

    @property
    def name(self) -> str: ...
    @property
    def access_flags(self) -> int: ...
    @access_flags.setter
    def access_flags(self, v: int) -> None: ...

    def set_code(self, code: CodeDef) -> None:
        """Attach a :class:`CodeDef` as this method's body."""
        ...

class IrClassDef:
    """A complete class definition for the DEX IR."""

    def __new__(cls, descriptor: str) -> IrClassDef: ...

    @property
    def descriptor(self) -> str: ...

    def set_access(self, flags: int) -> None: ...
    def set_superclass(self, desc: str) -> None: ...
    def add_interface(self, desc: str) -> None: ...
    def set_source_file(self, name: str) -> None: ...
    def add_static_field(
        self, name: str, field_type: str, access_flags: int = 0
    ) -> None: ...
    def add_instance_field(
        self, name: str, field_type: str, access_flags: int = 0
    ) -> None: ...
    def add_direct_method(self, method: IrMethodDef) -> None: ...
    def add_virtual_method(self, method: IrMethodDef) -> None: ...

class DexIrBuilder:
    """Builds a complete DEX file from class definitions."""

    def __new__(cls, version: int = 35) -> DexIrBuilder: ...

    def add_class(self, cls: IrClassDef) -> None:
        """Add a class to the IR (clones the class)."""
        ...

    def write(self) -> bytes:
        """Serialize all classes to a valid DEX byte string."""
        ...

    def class_count(self) -> int: ...
