import abc

# deprecated
class DexContainer(abc.ABC):
    def data(self) -> bytes: ...
    @property
    @abc.abstractmethod
    def file_size(self) -> int: ...

class InMemoryDexContainer:
    def __init__(self, data: bytes) -> None: ...
    def data(self) -> bytes: ...
    @property
    def file_size(self) -> int: ...
    def __len__(self) -> int: ...

class FileDexContainer:
    def __init__(self, path: str) -> None: ...
    def data(self) -> bytes: ...
    @property
    def file_size(self) -> int: ...
    @property
    def location(self) -> str: ...
    def __len__(self) -> int: ...
