def mutf8_to_str(utf8_data_in: bytes) -> str: ...
def str_to_mutf8(str_data_in: str) -> bytes: ...
def mutf8_to_str_lossy(utf8_data_in: bytes) -> str: ...
def str_to_mutf8_lossy(str_data_in: str) -> bytes: ...
