from . import (
    Instruction,
    PackedSwitchPayload,
    FillArrayDataPayload,
    SparseSwitchPayload,
)

def has_a(inst: Instruction) -> bool: ...
def has_b(inst: Instruction) -> bool: ...
def has_c(inst: Instruction) -> bool: ...
def has_h(inst: Instruction) -> bool: ...
def A(inst: Instruction) -> int: ...
def B(inst: Instruction) -> int: ...
def C(inst: Instruction) -> int: ...
def H(inst: Instruction) -> int: ...
def has_wide_b(inst: Instruction) -> bool: ...
def wide_b(inst: Instruction) -> int: ...
def array_data(inst: Instruction) -> FillArrayDataPayload: ...
def packed_switch(inst: Instruction) -> PackedSwitchPayload: ...
def sparse_switch(inst: Instruction) -> SparseSwitchPayload: ...
